[package]
name = "Transactions"
version = "0.1.0"
edition = "2021"

[dependencies]
ed25519-dalek = { version = "2.1.1", features = ["rand_core"] }
rand = "0.8.5"
blake3 = "1.5.5"
num-format = "0.4.4"
rayon = "1.10.0"

[profile.release]
debug = true